### PR TITLE
Add highlighting for SHEET and RULES sigils

### PR DESCRIPTION
**Pull request by NduatiK**
- [x] Get swift highlighting working
- [x] Isolate swift highlighting to inside do/end block

image

### CODE REVIEW

**Comment by bcardarella** [comment]
Looks good to me! @supernintendo or @carson-katri thoughts?

**Comment by bcardarella** [comment]
Actually, I did have one thought. We plan to have `~RULES` platform specific, so for Jetpack we'd presumably have a different syntax in that platform's `~RULES` sigil. Is there a way we can detect if this ruleset is for Swiftui?

**Review by carson-katri — APPROVED** [review]

**Comment by NduatiK** [comment]
It might be difficult to figure out the platform, unless we make use of modifiers eg `~RULES"""..."""swiftui`

**Comment by bcardarella** [comment]
is it possible to do so by looking for this line: `use LiveViewNative.Stylesheet, :swiftui` the 2nd arg being the platform in question

**Comment by NduatiK** [comment]
Yes, from some experimenting it looks like it is possible, but not a bit tricky. Can we handle formats in another PR? I've created an issue for this

**Comment by bcardarella** [comment]
@NduatiK yeah, we don't yet need the jetpack one yet so we can wait on it for now

**Pull request merged**
