### PR TITLE
Add syntax highlighting for the `style` attribute

### PR DESCRIPTION
**Pull request by carson-katri**
This adds syntax highlighting for the `style` attribute to `.neex` templates.

Screenshot 2024-05-16 at 3 47 59 PM

### CODE REVIEW

**Comment by bcardarella** [comment]
will this support the bracket forms as well:

```heex
<Button
  style={[
    "buttonBorderShape(.roundedRectangle(radius: 8))"
  ]}>
```

**Comment by carson-katri** [comment]
Currently it only supports `''` and `""`

**Comment by carson-katri** [comment]
I've added support for that syntax:

Screenshot 2024-05-16 at 4 16 42 PM

**Comment by carson-katri** [comment]
Added support for code completion to the attribute as well.

Screenshot 2024-05-16 at 4 33 37 PM

**Pull request merged**
